# -*- coding: utf-8 -*-
"""Le banc d'aiguillage, traduit a la main en anglais, allemand, espagnol.

Meme registre que l'original : banc_aiguillage est familier et fautif,
banc_neuf est indirect et poli. On traduit les mots, jamais l'intention.
"""
# (intention, fr, en, de, es)
FACILE = [
("image","tu peux me faire un dessin d'un chat astronaute","can you make me a drawing of an astronaut cat","kannst du mir eine Zeichnung von einer Astronautenkatze machen","puedes hacerme un dibujo de un gato astronauta"),
("image","genere un truc avec une foret magique stp","generate something with a magic forest pls","generier mir bitte was mit einem Zauberwald","genera algo con un bosque magico porfa"),
("image","jvoudrais un visuel d'une ville futuriste","i'd like a visual of a futuristic city","ich haett gern ein Bild von einer futuristischen Stadt","queria un visual de una ciudad futurista"),
("image","fait moi une illustration de dragon svp","make me a dragon illustration pls","mach mir bitte eine Drachen-Illustration","hazme una ilustracion de dragon porfa"),
("image","besoin d'un artwork fantaisie rapidos","need a fantasy artwork quick","brauch schnell ein Fantasy-Artwork","necesito un artwork de fantasia rapido"),
("image","cree qqch avec un coucher de soleil sur la mer","create smth with a sunset over the sea","erstell was mit einem Sonnenuntergang ueber dem Meer","crea algo con una puesta de sol sobre el mar"),
("edition","change la couleur du ciel sur cette photo","change the sky color on this photo","aender die Himmelsfarbe auf diesem Foto","cambia el color del cielo en esta foto"),
("edition","peux tu enlever le bouton la sur son manteau","can you remove the button there on his coat","kannst du den Knopf da an seinem Mantel entfernen","puedes quitar el boton ese de su abrigo"),
("edition","remplace le fond par une plage stp","replace the background with a beach pls","ersetz den Hintergrund bitte durch einen Strand","reemplaza el fondo por una playa porfa"),
("edition","ajoute des lunettes au personnage","add glasses to the character","fueg der Figur eine Brille hinzu","anade gafas al personaje"),
("edition","jveux modif la couleur des cheveux","i wanna change the hair color","will die Haarfarbe aendern","quiero cambiar el color del pelo"),
("edition","efface la personne a droite sur l image","erase the person on the right in the image","loesch die Person rechts im Bild","borra a la persona de la derecha en la imagen"),
("agrandir","peux tu agrandir cette photo sans la deformer","can you enlarge this photo without distorting it","kannst du dieses Foto vergroessern ohne es zu verzerren","puedes agrandar esta foto sin deformarla"),
("agrandir","jvoudrai une version plus grande de l image","i'd like a bigger version of the image","ich haett gern eine groessere Version vom Bild","queria una version mas grande de la imagen"),
("agrandir","upscale moi ca stp","upscale this for me pls","upscale mir das bitte","hazme un upscale de esto porfa"),
("agrandir","augmente la resolution sans changer le contenu","increase the resolution without changing the content","erhoehe die Aufloesung ohne den Inhalt zu aendern","aumenta la resolucion sin cambiar el contenido"),
("agrandir","rend cette image plus grande sans perte","make this image bigger without loss","mach dieses Bild groesser ohne Verlust","haz esta imagen mas grande sin perdida"),
("agrandir","faut zoomer sur cette pic sans la casser","gotta zoom on this pic without breaking it","muss auf dieses Pic zoomen ohne es kaputt zu machen","hay que hacer zoom en esta pic sin romperla"),
("detourer","enleve le fond de cette photo stp","remove the background of this photo pls","entferne bitte den Hintergrund von diesem Foto","quita el fondo de esta foto porfa"),
("detourer","jveux isoler juste le sujet sur l image","i want to isolate just the subject in the image","ich will nur das Motiv im Bild freistellen","quiero aislar solo el sujeto en la imagen"),
("detourer","peux tu detourer la personne du fond blanc","can you cut out the person from the white background","kannst du die Person vom weissen Hintergrund freistellen","puedes recortar a la persona del fondo blanco"),
("detourer","retire l arriere plan de cette pic","take out the background of this pic","nimm den Hintergrund von diesem Pic weg","retira el fondo de esta pic"),
("detourer","faut extraire juste l objet sans le decor","gotta extract just the object without the scenery","muss nur das Objekt ohne die Kulisse extrahieren","hay que extraer solo el objeto sin el decorado"),
("detourer","supprime tout sauf le personnage stp","delete everything except the character pls","loesch bitte alles ausser der Figur","elimina todo menos el personaje porfa"),
("video","cree une video d'un feu d'artifice","create a video of fireworks","erstell ein Video von einem Feuerwerk","crea un video de fuegos artificiales"),
("video","jveux un clip d'une voiture qui roule en ville","i want a clip of a car driving in the city","ich will einen Clip von einem Auto das durch die Stadt faehrt","quiero un clip de un coche circulando por la ciudad"),
("video","genere moi une sequence de vagues sur la plage","generate me a sequence of waves on the beach","generier mir eine Sequenz von Wellen am Strand","generame una secuencia de olas en la playa"),
("video","fait une petite vid d'un robot qui marche","make a short vid of a robot walking","mach ein kurzes Vid von einem Roboter der laeuft","haz un video corto de un robot que camina"),
("video","besoin d'une video de zero avec un dragon qui vole","need a video from scratch with a flying dragon","brauche ein Video von null mit einem fliegenden Drachen","necesito un video desde cero con un dragon que vuela"),
("video","cree un film court d'une foret enchantee","create a short film of an enchanted forest","erstell einen Kurzfilm von einem verzauberten Wald","crea un cortometraje de un bosque encantado"),
("video_image","anime cette photo de mon chat stp","animate this photo of my cat pls","animier bitte dieses Foto von meiner Katze","anima esta foto de mi gato porfa"),
("video_image","fait bouger le perso sur cette image","make the character move in this image","lass die Figur auf diesem Bild sich bewegen","haz que se mueva el personaje en esta imagen"),
("video_image","jveux que cette photo devienne animee","i want this photo to become animated","ich will dass dieses Foto animiert wird","quiero que esta foto se vuelva animada"),
("video_image","peux tu donner vie a cette illustration","can you bring this illustration to life","kannst du diese Illustration zum Leben erwecken","puedes dar vida a esta ilustracion"),
("video_image","transforme cette image en petite animation","turn this image into a small animation","verwandle dieses Bild in eine kleine Animation","transforma esta imagen en una pequena animacion"),
("video_image","fait bouger les cheveux sur cette pic stp","make the hair move in this pic pls","lass bitte die Haare auf diesem Pic sich bewegen","haz que se mueva el pelo en esta pic porfa"),
("fluidifier","rend cette video plus fluide stp","make this video smoother pls","mach dieses Video bitte fluessiger","haz este video mas fluido porfa"),
("fluidifier","jveux un ralenti sur ce clip","i want a slow motion on this clip","ich will eine Zeitlupe auf diesem Clip","quiero una camara lenta en este clip"),
("fluidifier","peux tu ameliorer les fps de la vid","can you improve the fps of the vid","kannst du die fps vom Vid verbessern","puedes mejorar los fps del video"),
("fluidifier","cette video saccade, arrange ca","this video stutters, fix that","dieses Video ruckelt, richte das","este video da tirones, arregla eso"),
("fluidifier","fait un slowmo sur ce passage","do a slowmo on this part","mach ein Slowmo auf dieser Stelle","haz un slowmo en este trozo"),
("fluidifier","lisse le mouvement de cette video stp","smooth the motion of this video pls","glaette bitte die Bewegung von diesem Video","suaviza el movimiento de este video porfa"),
("audio","cree une musique triste au piano","create a sad piano music","erstell eine traurige Klaviermusik","crea una musica triste al piano"),
("audio","jveux une chanson entrainante pour l'ete","i want an upbeat song for the summer","ich will einen mitreissenden Song fuer den Sommer","quiero una cancion animada para el verano"),
("audio","genere un beat hip hop stp","generate a hip hop beat pls","generier bitte einen Hip-Hop-Beat","genera un beat de hip hop porfa"),
("audio","fait moi un morceau instru relaxant","make me a relaxing instrumental track","mach mir einen entspannenden Instrumentaltrack","hazme un tema instrumental relajante"),
("audio","besoin d'une melodie douce pour dormir","need a soft melody for sleeping","brauche eine sanfte Melodie zum Einschlafen","necesito una melodia suave para dormir"),
("audio","compose un son epique pour une bande annonce","compose an epic sound for a trailer","komponier einen epischen Sound fuer einen Trailer","compon un sonido epico para un trailer"),
("planche","fait moi une planche de bd avec 4 cases","make me a comic page with 4 panels","mach mir eine Comicseite mit 4 Panels","hazme una pagina de comic con 4 vinetas"),
("planche","jveux une page manga avec plusieurs cases","i want a manga page with several panels","ich will eine Mangaseite mit mehreren Panels","quiero una pagina de manga con varias vinetas"),
("planche","cree une bd courte sur un super heros","create a short comic about a superhero","erstell einen kurzen Comic ueber einen Superhelden","crea un comic corto sobre un superheroe"),
("planche","genere une page comics avec dialogue","generate a comics page with dialogue","generier eine Comicseite mit Dialog","genera una pagina de comic con dialogo"),
("planche","faut une planche avec 6 vignettes stp","need a board with 6 panels pls","brauche bitte eine Seite mit 6 Panels","hace falta una plancha con 6 vinetas porfa"),
("planche","dessine une histoire en cases genre bd","draw a story in panels like a comic","zeichne eine Geschichte in Panels wie ein Comic","dibuja una historia en vinetas tipo comic"),
("objet3d","cree un objet 3d d'une voiture","create a 3d object of a car","erstell ein 3d-Objekt von einem Auto","crea un objeto 3d de un coche"),
("objet3d","jveux un modele 3d d'une chaise","i want a 3d model of a chair","ich will ein 3d-Modell von einem Stuhl","quiero un modelo 3d de una silla"),
("objet3d","genere une figurine 3d de dragon","generate a 3d dragon figurine","generier eine 3d-Drachenfigur","genera una figura 3d de dragon"),
("objet3d","fait moi un rendu 3d d'un vaisseau spatial","make me a 3d render of a spaceship","mach mir ein 3d-Rendering von einem Raumschiff","hazme un render 3d de una nave espacial"),
("objet3d","besoin d'un modele en volume pour impression 3d","need a volume model for 3d printing","brauche ein Volumenmodell fuer den 3d-Druck","necesito un modelo en volumen para impresion 3d"),
("objet3d","cree une sculpture numerique 3d stp","create a 3d digital sculpture pls","erstell bitte eine digitale 3d-Skulptur","crea una escultura digital 3d porfa"),
("lecture","dis moi ce qu'il y a sur cette photo","tell me what's in this photo","sag mir was auf diesem Foto ist","dime que hay en esta foto"),
("lecture","decris moi cette image stp","describe this image to me pls","beschreib mir bitte dieses Bild","describeme esta imagen porfa"),
("lecture","c'est quoi sur cette pic exactement","what is on this pic exactly","was ist auf diesem Pic genau","que hay en esta pic exactamente"),
("lecture","explique ce que tu vois sur l'image","explain what you see in the image","erklaer was du auf dem Bild siehst","explica lo que ves en la imagen"),
("lecture","jvoudrais savoir ce qui est represente ici","i'd like to know what is depicted here","ich wuesste gern was hier dargestellt ist","queria saber que esta representado aqui"),
("lecture","peux tu analyser cette photo et me dire ce que c'est","can you analyze this photo and tell me what it is","kannst du dieses Foto analysieren und mir sagen was es ist","puedes analizar esta foto y decirme que es"),
]

DUR = [
("image","Il me faudrait une illustration d'un dragon dans un ciel orageux.","I would need an illustration of a dragon in a stormy sky.","Ich braeuchte eine Illustration von einem Drachen in einem stuermischen Himmel.","Me haria falta una ilustracion de un dragon en un cielo tormentoso."),
("image","Est-ce que tu saurais me sortir un visuel de paysage montagneux, style aquarelle ?","Could you come up with a mountain landscape visual, watercolour style?","Koenntest du mir ein Bergland-Motiv im Aquarellstil hinbekommen?","Sabrias sacarme un visual de paisaje montanoso, estilo acuarela?"),
("image","Pour mon projet scolaire, j'aurais besoin d'une representation d'un robot futuriste.","For my school project, I would need a depiction of a futuristic robot.","Fuer mein Schulprojekt braeuchte ich eine Darstellung eines futuristischen Roboters.","Para mi proyecto escolar, necesitaria una representacion de un robot futurista."),
("image","Une illustration facon Miyazaki, tu peux ?","An illustration in the Miyazaki manner, can you?","Eine Illustration a la Miyazaki, kannst du?","Una ilustracion al estilo Miyazaki, puedes?"),
("edition","Cette photo manque un peu de peps, tu pourrais ajuster les couleurs ?","This photo lacks a bit of punch, could you adjust the colours?","Diesem Foto fehlt es etwas an Pep, koenntest du die Farben anpassen?","A esta foto le falta un poco de chispa, podrias ajustar los colores?"),
("edition","Il faudrait revoir la luminosite de ce cliche de mariage.","The brightness of this wedding shot ought to be reworked.","Die Helligkeit dieser Hochzeitsaufnahme muesste ueberarbeitet werden.","Habria que revisar la luminosidad de esta toma de boda."),
("edition","J'aimerais retoucher les contrastes sur cette photo de portrait.","I would like to rework the contrast on this portrait photo.","Ich wuerde gern die Kontraste auf diesem Portraitfoto nachbearbeiten.","Me gustaria retocar los contrastes en esta foto de retrato."),
("edition","Petite retouche de teintes","Small tint touch-up","Kleine Farbtonkorrektur","Pequeno retoque de tonos"),
("agrandir","Cette icone est vraiment trop petite pour l'impression, il faudrait la rendre plus grande.","This icon is really too small for printing, it would need to be made bigger.","Dieses Icon ist wirklich zu klein fuer den Druck, es muesste groesser gemacht werden.","Este icono es realmente demasiado pequeno para la impresion, habria que hacerlo mas grande."),
("agrandir","Est-ce que tu saurais faire en sorte que cette image tienne sur une affiche geante sans perdre en qualite ?","Could you make this image fit a giant poster without losing quality?","Koenntest du dafuer sorgen, dass dieses Bild auf ein Riesenplakat passt ohne an Qualitaet zu verlieren?","Sabrias hacer que esta imagen quepa en un cartel gigante sin perder calidad?"),
("agrandir","J'ai besoin d'une version haute resolution de ce logo minuscule.","I need a high resolution version of this tiny logo.","Ich brauche eine hochaufloesende Version von diesem winzigen Logo.","Necesito una version de alta resolucion de este logo minusculo."),
("agrandir","Plus grand, s'il te plait","Bigger, please","Groesser, bitte","Mas grande, por favor"),
("detourer","Le fond de cette photo de produit me derange, on pourrait l'enlever ?","The background of this product photo bothers me, could we remove it?","Der Hintergrund von diesem Produktfoto stoert mich, koennten wir ihn entfernen?","El fondo de esta foto de producto me molesta, podriamos quitarlo?"),
("detourer","Il me faudrait isoler ce personnage du reste du decor.","I would need to isolate this character from the rest of the scenery.","Ich muesste diese Figur vom Rest der Kulisse freistellen.","Me haria falta aislar a este personaje del resto del decorado."),
("detourer","Pour ma fiche produit Amazon, il faudrait un fond blanc a la place de celui-ci.","For my Amazon product listing, a white background would be needed instead of this one.","Fuer meine Amazon-Produktseite braeuchte es einen weissen Hintergrund statt diesem.","Para mi ficha de producto de Amazon, haria falta un fondo blanco en lugar de este."),
("detourer","Suppression du fond","Background removal","Hintergrundentfernung","Eliminacion del fondo"),
("video","Est-ce que tu saurais me creer une petite sequence animee d'une ville la nuit ?","Could you create me a short animated sequence of a city at night?","Koenntest du mir eine kurze animierte Sequenz von einer Stadt bei Nacht erstellen?","Sabrias crearme una pequena secuencia animada de una ciudad de noche?"),
("video","Il me faudrait un clip de quelques secondes montrant des vagues sur la plage.","I would need a few-second clip showing waves on the beach.","Ich braeuchte einen Clip von wenigen Sekunden, der Wellen am Strand zeigt.","Me haria falta un clip de unos segundos mostrando olas en la playa."),
("video","Pour ma presentation, j'aurais besoin d'une animation d'un logo qui apparait progressivement.","For my presentation, I would need an animation of a logo appearing progressively.","Fuer meine Praesentation braeuchte ich eine Animation von einem Logo, das nach und nach erscheint.","Para mi presentacion, necesitaria una animacion de un logo que aparece progresivamente."),
("video","Un petit teaser anime, facon Pixar","A short animated teaser, Pixar style","Ein kurzer animierter Teaser, a la Pixar","Un pequeno teaser animado, al estilo Pixar"),
("video_image","J'ai cette vieille cassette, tu saurais en extraire une image fixe precise ?","I have this old tape, could you extract a precise still image from it?","Ich habe diese alte Kassette, koenntest du daraus ein genaues Standbild ziehen?","Tengo esta vieja cinta, sabrias extraer de ella una imagen fija precisa?"),
("video_image","Il me faudrait transformer cette photo de mon chat en une petite sequence animee.","I would need to turn this photo of my cat into a short animated sequence.","Ich muesste dieses Foto von meiner Katze in eine kurze animierte Sequenz verwandeln.","Me haria falta transformar esta foto de mi gato en una pequena secuencia animada."),
("video_image","Est-ce que tu pourrais convertir ce clip en une serie de captures ?","Could you convert this clip into a series of stills?","Koenntest du diesen Clip in eine Reihe von Einzelbildern umwandeln?","Podrias convertir este clip en una serie de capturas?"),
("video_image","De la photo a l'animation, c'est possible ?","From photo to animation, is that possible?","Vom Foto zur Animation, ist das moeglich?","De la foto a la animacion, es posible?"),
("fluidifier","Ce clip saccade un peu, tu pourrais arranger ca ?","This clip stutters a bit, could you fix that?","Dieser Clip ruckelt ein wenig, koenntest du das richten?","Este clip da un poco de tirones, podrias arreglar eso?"),
("fluidifier","Il me faudrait rendre les mouvements plus naturels dans cette animation.","I would need to make the movements more natural in this animation.","Ich muesste die Bewegungen in dieser Animation natuerlicher machen.","Me haria falta hacer los movimientos mas naturales en esta animacion."),
("fluidifier","Est-ce que tu saurais ameliorer la frequence d'images de cette video un peu saccadee ?","Could you improve the frame rate of this slightly stuttering video?","Koenntest du die Bildrate von diesem etwas ruckelnden Video verbessern?","Sabrias mejorar la frecuencia de imagenes de este video un poco entrecortado?"),
("fluidifier","Mouvements plus doux, tu geres ?","Smoother movements, can you handle it?","Sanftere Bewegungen, kriegst du das hin?","Movimientos mas suaves, te encargas?"),
("audio","Il me faudrait une petite musique d'ambiance pour ma video de vacances.","I would need a little background music for my holiday video.","Ich braeuchte eine kleine Hintergrundmusik fuer mein Urlaubsvideo.","Me haria falta una pequena musica de ambiente para mi video de vacaciones."),
("audio","Est-ce que tu saurais composer un jingle pour mon podcast ?","Could you compose a jingle for my podcast?","Koenntest du einen Jingle fuer meinen Podcast komponieren?","Sabrias componer un jingle para mi podcast?"),
("audio","Pour Halloween, j'aurais besoin d'un fond sonore inquietant.","For Halloween, I would need an unsettling soundscape.","Fuer Halloween braeuchte ich eine beunruhigende Klangkulisse.","Para Halloween, necesitaria un fondo sonoro inquietante."),
("audio","Une petite melodie relaxante, facon Enya ?","A short relaxing melody, Enya style?","Eine kleine entspannende Melodie, a la Enya?","Una pequena melodia relajante, al estilo Enya?"),
("planche","Pour presenter mon travail, il me faudrait un assemblage de plusieurs vignettes sur une seule page.","To present my work, I would need an assembly of several panels on a single page.","Um meine Arbeit zu praesentieren, braeuchte ich eine Zusammenstellung mehrerer Panels auf einer einzigen Seite.","Para presentar mi trabajo, me haria falta un montaje de varias vinetas en una sola pagina."),
("planche","Est-ce que tu saurais organiser mes croquis facon storyboard ?","Could you lay out my sketches storyboard style?","Koenntest du meine Skizzen im Storyboard-Stil anordnen?","Sabrias organizar mis bocetos al estilo storyboard?"),
("planche","J'aimerais regrouper ces cases de BD sur un meme document.","I would like to gather these comic panels onto one document.","Ich wuerde gern diese Comic-Panels auf einem Dokument zusammenfassen.","Me gustaria agrupar estas vinetas de comic en un mismo documento."),
("planche","Mise en page facon manga","Manga style page layout","Seitenlayout im Manga-Stil","Maquetacion al estilo manga"),
("objet3d","Pour mon jeu video, il me faudrait un modele tridimensionnel de personnage.","For my video game, I would need a three-dimensional character model.","Fuer mein Videospiel braeuchte ich ein dreidimensionales Figurenmodell.","Para mi videojuego, me haria falta un modelo tridimensional de personaje."),
("objet3d","Est-ce que tu saurais concevoir une figurine numerique d'un vaisseau spatial ?","Could you design a digital figurine of a spaceship?","Koenntest du eine digitale Figur von einem Raumschiff entwerfen?","Sabrias disenar una figura digital de una nave espacial?"),
("objet3d","J'aurais besoin d'une forme en volume pour l'impression sur mon imprimante, facon Prusa.","I would need a volume shape for printing on my printer, Prusa style.","Ich braeuchte eine Volumenform fuer den Druck auf meinem Drucker, a la Prusa.","Necesitaria una forma en volumen para la impresion en mi impresora, tipo Prusa."),
("objet3d","Un asset en volume, tu peux ?","A volume asset, can you?","Ein Asset in Volumen, kannst du?","Un asset en volumen, puedes?"),
("lecture","Je voudrais ecouter ce fichier avant de l'envoyer au client.","I would like to listen to this file before sending it to the client.","Ich wuerde gern diese Datei anhoeren, bevor ich sie an den Kunden schicke.","Queria escuchar este archivo antes de enviarlo al cliente."),
("lecture","Est-ce que tu saurais me faire entendre ce message vocal ?","Could you let me hear this voice message?","Koenntest du mir diese Sprachnachricht vorspielen?","Sabrias hacerme oir este mensaje de voz?"),
("lecture","Il me faudrait passer ce morceau pour verifier le rendu final.","I would need to play this track to check the final result.","Ich muesste dieses Stueck abspielen, um das Endergebnis zu pruefen.","Me haria falta poner este tema para verificar el resultado final."),
("lecture","Diffusion du fichier, s'il te plait","Play the file, please","Datei abspielen, bitte","Reproduccion del archivo, por favor"),
("image","Un magnifique fond d'ecran du jeu Halo avec Masterchief, pleins de details du jeu en bonne qualite et en 1920x1080","A magnificent wallpaper of the game Halo with Masterchief, lots of game details in good quality and in 1920x1080","Ein prachtvolles Hintergrundbild vom Spiel Halo mit Masterchief, viele Spieldetails in guter Qualitaet und in 1920x1080","Un magnifico fondo de pantalla del juego Halo con Masterchief, lleno de detalles del juego en buena calidad y en 1920x1080"),
("image","un paysage de montagne en 4k avec beaucoup de details","a mountain landscape in 4k with lots of details","eine Berglandschaft in 4k mit vielen Details","un paisaje de montana en 4k con muchos detalles"),
("image","une affiche de film en haute definition, tres detaillee","a movie poster in high definition, very detailed","ein Filmplakat in hoher Aufloesung, sehr detailliert","un cartel de pelicula en alta definicion, muy detallado"),
("image","un portrait de studio en 1920x1080, qualite professionnelle","a studio portrait in 1920x1080, professional quality","ein Studioportrait in 1920x1080, professionelle Qualitaet","un retrato de estudio en 1920x1080, calidad profesional"),
("image","une voiture de sport rouge, rendu de tres bonne qualite","a red sports car, very good quality render","ein roter Sportwagen, Rendering von sehr guter Qualitaet","un coche deportivo rojo, render de muy buena calidad"),
]
